// ============================================================
// 🎨 Creative Shop Dashboard — Personal Configuration
// Generated by Setup Wizard on March 16, 2026
// ============================================================

export const dashboardConfig = {
  profile: {
    name: "Pedro Menezes",
    firstName: "Pedro",
    role: "Creative Strategist",
    team: "CS Americas - LATAM",
    company: "Meta",
    territory: "Brazil (GBG-LATAM)",
    manager: "Gustavo Borrmann",
    initials: "PM",
    avatarColor: "#7C3AED",
    isInOffice: true,
  },

  unidash: {
    salesRepName: "Pedro Menezes",
    quarter: "Q1 2026",
    ciMinTarget: 3,
    ciUrl: "https://www.internalfb.com/unidash/dashboard/engagement_management_process_dashboard/dcmp_client_interaction_insights/",
    aiUsageUrl: "https://www.internalfb.com/unidash/dashboard/ai_usage_at_meta/ai4p_by_pillar/my_ai_usage",
  },

  crm: {
    // CI filter: Participant is in my BoB + This Quarter + Is qualified + Participant contains any of [Your Name]
    // Auto-generated from your internal FBID — do not edit manually
    ciUrl: "https://www.internalfb.com/crm/client_interactions?direction=&filters=[%7B%22field%22%3A%22participant%22%2C%22operator%22%3A%22fbid_set_participant_in_book_of_business%22%2C%22value%22%3A%7B%22type%22%3A%22empty%22%7D%7D%2C%7B%22field%22%3A%22interaction_time%22%2C%22operator%22%3A%22timestamp_in_range_within_this_quarter%22%2C%22value%22%3A%7B%22type%22%3A%22empty%22%7D%7D%2C%7B%22field%22%3A%22is_qualified%22%2C%22operator%22%3A%22bool_is_true%22%2C%22value%22%3A%7B%22type%22%3A%22empty%22%7D%7D%2C%7B%22field%22%3A%22participant%22%2C%22operator%22%3A%22fbid_set_contains_any%22%2C%22value%22%3A%7B%22type%22%3A%22entity_list%22%2C%22value%22%3A[%7B%22fbid%22%3A%221084877300%22%2C%22label%22%3A%22Pedro%20Menezes%22%7D]%7D%7D]&relativeDateRange=&showCount=false&sortKey=",
    fbid: "",
  },

  workplace: {
    primaryGroup: {
      name: "CS: The Work",
      url: "https://fb.workplace.com/groups/365231093525512",
    },
    groups: [],
    scrapeFeed: false,
    feedUrl: "https://fb.workplace.com",
  },

  calendarUrl: "https://www.internalfb.com/calendar",

  appearance: {
    sidebarAccentColor: "#1a1f36",
    primaryColor: "#0a0a0a",
    secondaryColor: "#0064E0",
    greeting: "Good morning",
  },

  schedule: {
    dailyRefreshTime: "07:00",
    timezone: "America/Sao_Paulo",
  },

  clients: [
    {
      id: "magazine-luiza",
      name: "Magazine Luiza",
      shortName: "Magazine Luiza",
      tier: "A",
      color: "#0064E0",
      lightColor: "#F5F5FF",
      logo: "🏢",
      summary: "",
      materials: [],
    },
    {
      id: "amazon.com",
      name: "Amazon.Com",
      shortName: "Amazon",
      tier: "A",
      color: "#e08300",
      lightColor: "#F5F5FF",
      logo: "🏢",
      summary: "",
      materials: [],
    },
    {
      id: "samsung-electronics-co-ltd---kr(usd)",
      name: "Samsung Electronics Co Ltd - KR(USD)",
      shortName: "Samsung",
      tier: "A",
      color: "#7b00e0",
      lightColor: "#F5F5FF",
      logo: "🏢",
      summary: "",
      materials: [],
    }
  ],
};

export type DashboardConfig = typeof dashboardConfig;
