// ============================================================
// Creative Shop Dashboard — Core Data
// User identity and client portfolio are driven by dashboard.config.ts
// ============================================================

import { dashboardConfig } from "./dashboard.config";

export const userProfile = {
  name: dashboardConfig.profile.name,
  role: dashboardConfig.profile.role,
  team: dashboardConfig.profile.team,
  company: dashboardConfig.profile.company,
  territory: dashboardConfig.profile.territory,
  manager: dashboardConfig.profile.manager,
  level: dashboardConfig.profile.level,
  rating: "Exceeded Expectations",
};

// ─── CLIENTS ────────────────────────────────────────────────
// Driven by dashboard.config.ts — edit clients there, not here.
// Fields like totalAR, csEligibleAR, activeProjects are refreshed by Manus on each data update.
export const clients = dashboardConfig.clients.map((c, i) => ({
  id: c.id,
  name: c.name,
  shortName: c.shortName,
  tier: c.tier,
  priority: i + 1,
  color: c.color,
  lightColor: c.lightColor ?? "#F5F5FF",
  borderColor: c.color,
  totalAR: 0,
  csEligibleAR: 0,
  globalAR: null as number | null,
  csServiceLevel: "Dedicated: Proactive",
  totalRSes: 0,
  q1Eligible: true,
  q2Eligible: true,
  logo: c.logo ?? "🏢",
  summary: c.summary,
  activeProjects: [] as string[],
  contacts: {
    internal: `${dashboardConfig.profile.name} (CS) + ${dashboardConfig.profile.manager} (Manager)`,
    meetingCadence: "Weekly sync",
  },
}));

// ─── RECOMMENDED SOLUTIONS ──────────────────────────────────
export const recommendedSolutions = [
  // Magazine Luiza
  {
    id: "rs-1",
    clientId: "magalu",
    rsName: "Catalog Product Level Video: Creative",
    product: "A+ Catalog",
    stage: "ACTIONED",
    arHeadroom: 1426089,
    targetClose: "Feb 2026",
    priority: 1,
  },
  {
    id: "rs-2",
    clientId: "magalu",
    rsName: "Catalog Product Level Video: Creative",
    product: "A+ Catalog",
    stage: "ADOPTED",
    arHeadroom: 479381,
    targetClose: "Complete",
    priority: 2,
  },
  {
    id: "rs-3",
    clientId: "magalu",
    rsName: "Scale partnership ads in more campaigns",
    product: "Partnership Ads",
    stage: "ACTIONED",
    arHeadroom: 306893,
    targetClose: "Q1 2026",
    priority: 3,
  },
  {
    id: "rs-4",
    clientId: "magalu",
    rsName: "Automation Sales",
    product: "Automation Sales AU",
    stage: "CLOSED",
    arHeadroom: 269797,
    targetClose: "Complete",
    priority: 4,
  },
  {
    id: "rs-5",
    clientId: "magalu",
    rsName: "Creative: Increase Creative Diversification",
    product: "Creative Diversity",
    stage: "SCOPING",
    arHeadroom: 75000,
    targetClose: "Q2 2026",
    priority: 5,
  },
  // Samsung
  {
    id: "rs-6",
    clientId: "samsung",
    rsName: "Adopt CTX",
    product: "CTX",
    stage: "DISCOVERY",
    arHeadroom: 970952,
    targetClose: "Mar 2026",
    priority: 1,
  },
  {
    id: "rs-7",
    clientId: "samsung",
    rsName: "Creative: Increase Creative Diversification",
    product: "Creative Diversity",
    stage: "ADOPTED",
    arHeadroom: 574000,
    targetClose: "Complete",
    priority: 2,
  },
  {
    id: "rs-8",
    clientId: "samsung",
    rsName: "Scale partnership ads in more campaigns",
    product: "Partnership Ads",
    stage: "ACTIONED",
    arHeadroom: 567500,
    targetClose: "Mar 2026",
    priority: 3,
  },
  {
    id: "rs-9",
    clientId: "samsung",
    rsName: "Adopt CTX",
    product: "CTX",
    stage: "ACTIONED",
    arHeadroom: 114791,
    targetClose: "Mar 2026",
    priority: 4,
  },
  {
    id: "rs-10",
    clientId: "samsung",
    rsName: "Creative: Increase Creative Diversification",
    product: "Creative Diversity",
    stage: "ACTIONED",
    arHeadroom: 238040,
    targetClose: "Mar 2026",
    priority: 5,
  },
  // Amazon
  {
    id: "rs-11",
    clientId: "amazon",
    rsName: "Catalog Product Level Video: Creative",
    product: "A+ Catalog",
    stage: "PITCHING",
    arHeadroom: 1006877,
    targetClose: "Feb 2026",
    priority: 1,
  },
  {
    id: "rs-12",
    clientId: "amazon",
    rsName: "Scale partnership ads in more campaigns",
    product: "Partnership Ads",
    stage: "ACTIONED",
    arHeadroom: 613829,
    targetClose: "Feb 2026",
    priority: 2,
  },
  {
    id: "rs-13",
    clientId: "amazon",
    rsName: "Advantage+ campaign budget",
    product: "Advantage+",
    stage: "PARTIALLY_ADOPTED",
    arHeadroom: 282721,
    targetClose: "Q1 2026",
    priority: 3,
  },
  {
    id: "rs-14",
    clientId: "amazon",
    rsName: "Simplify: Optimize Account Structure",
    product: "Simplification",
    stage: "PARTIALLY_ADOPTED",
    arHeadroom: 234803,
    targetClose: "Q1 2026",
    priority: 4,
  },
  {
    id: "rs-15",
    clientId: "amazon",
    rsName: "Opt into Reels placements using 9:16 video",
    product: "Reels",
    stage: "ACTIONED",
    arHeadroom: 175344,
    targetClose: "Q1 2026",
    priority: 5,
  },
  // ABI
  {
    id: "rs-16",
    clientId: "abi",
    rsName: "Creative: Increase Creative Diversification",
    product: "Creative Diversity",
    stage: "PARTIALLY_ADOPTED",
    arHeadroom: 752539,
    targetClose: "Mar 2026",
    priority: 1,
  },
  {
    id: "rs-17",
    clientId: "abi",
    rsName: "Scale partnership ads in more campaigns",
    product: "Partnership Ads",
    stage: "ACTIONED",
    arHeadroom: 523466,
    targetClose: "Mar 2026",
    priority: 2,
  },
  {
    id: "rs-18",
    clientId: "abi",
    rsName: "OS: Drive Brand Best Practice Adoption",
    product: "Brand",
    stage: "CLOSED",
    arHeadroom: 291534,
    targetClose: "Complete",
    priority: 3,
  },
  {
    id: "rs-19",
    clientId: "abi",
    rsName: "Full Funnel Campaign",
    product: "Campaign",
    stage: "CLOSED_WON",
    arHeadroom: 100000,
    targetClose: "Complete",
    priority: 4,
  },
];

// ─── MEETINGS ───────────────────────────────────────────────
export const meetings = [
  // ── Last week (past): Mar 2–6, 2026 ──
  {
    id: "m-mon-1",
    title: "Pedro & Gus - Performance Review",
    date: "2026-03-02",
    time: "10:15 AM",
    duration: "45 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Gustavo Borrmann"],
    topic: "Performance review sync with manager",
    platform: "Meta Calendar",
    status: "past",
  },
  {
    id: "m-mon-2",
    title: "Alinhamento Workshop para Amazon na Copa",
    date: "2026-03-02",
    time: "2:00 PM",
    duration: "30 min",
    type: "Client",
    clientId: "amazon",
    attendees: [dashboardConfig.profile.name, "Amazon Brazil Team"],
    topic: "Workshop alignment for Amazon World Cup campaign",
    platform: "SAO3732.09 Masmorras e Dragões",
    status: "past",
  },
  {
    id: "m-mon-3",
    title: "CS Opex Request Office Hours (Americas & EMEA)",
    date: "2026-03-02",
    time: "2:30 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "CS Team"],
    topic: "Office hours for CS Opex requests",
    platform: "SAO3732.09 Largo da Batata",
    status: "past",
  },
  {
    id: "m-mon-4",
    title: "CS LATAM Team meeting",
    date: "2026-03-02",
    time: "3:30 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "CS LATAM Team"],
    topic: "Weekly CS LATAM team sync",
    platform: "SAO3732.09 Largo da Batata",
    status: "past",
  },
  {
    id: "m-mon-5",
    title: "Global ABI Core Team Weekly",
    date: "2026-03-02",
    time: "4:30 PM",
    duration: "60 min",
    type: "Client",
    clientId: "abi",
    attendees: [dashboardConfig.profile.name, "ABI Global Core Team"],
    topic: "Global ABI weekly core team sync",
    platform: "SAO3732.09 Ladeira Porto Geral",
    status: "past",
  },
  {
    id: "m-tue-1",
    title: "Breath Lab - Weekly",
    date: "2026-03-03",
    time: "9:30 AM",
    duration: "30 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Breath Lab Team"],
    topic: "Weekly Breath Lab session",
    platform: "SAO3732.09 One room to rule them all",
    status: "past",
  },
  {
    id: "m-tue-2",
    title: "Measuring Cross-Channel Impact with Meta Conversion Lift",
    date: "2026-03-03",
    time: "1:00 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Meta Team"],
    topic: "Cross-channel measurement with Meta Conversion Lift",
    platform: "Virtual",
    status: "past",
  },
  {
    id: "m-wed-1",
    title: "Global ABI Monthly Community Call",
    date: "2026-03-04",
    time: "11:00 AM",
    duration: "60 min",
    type: "Client",
    clientId: "abi",
    attendees: [dashboardConfig.profile.name, "ABI Global Community"],
    topic: "Monthly ABI global community call",
    platform: "SAO3732.10 Zilda Arns",
    status: "past",
  },
  {
    id: "m-wed-2",
    title: "Meta & AlmapBBDO | Creative Workshop para Amazon na Copa",
    date: "2026-03-04",
    time: "2:00 PM",
    duration: "60 min",
    type: "Client",
    clientId: "amazon",
    attendees: [dashboardConfig.profile.name, "AlmapBBDO Team", "Amazon Brazil"],
    topic: "Creative workshop for Amazon World Cup campaign with AlmapBBDO",
    platform: "SAO3732.07 Daora",
    status: "past",
  },
  {
    id: "m-wed-3",
    title: "Seeds & Sequoias: CS Americas Monthly Workshare",
    date: "2026-03-04",
    time: "3:30 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "CS Americas Team"],
    topic: "Monthly CS Americas workshare session",
    platform: "SAO3732.09 Largo da Batata",
    status: "past",
  },
  {
    id: "m-thu-1",
    title: "Maximize lead quality with signal Solutions Live",
    date: "2026-03-05",
    time: "1:00 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Solutions Team"],
    topic: "Solutions Live session on lead quality with signal",
    platform: "Virtual",
    status: "past",
  },
  {
    id: "m-thu-2",
    title: "[Q&A] Latam GBG + Mexico Office Q&A with Latam GBG LT",
    date: "2026-03-05",
    time: "4:00 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Latam GBG LT", "Mexico Office"],
    topic: "Q&A session with Latam GBG leadership team",
    platform: "Virtual",
    status: "past",
  },
  {
    id: "m-fri-1",
    title: "Oakley Meta + ABI (Corona) | World Cup",
    date: "2026-03-06",
    time: "2:00 PM",
    duration: "60 min",
    type: "Client",
    clientId: "abi",
    attendees: [dashboardConfig.profile.name, "Oakley Team", "ABI Corona Team"],
    topic: "World Cup campaign alignment between Oakley Meta and ABI Corona",
    platform: "Virtual",
    status: "past",
  },
  {
    id: "m-fri-2",
    title: "ABI US x Meta - FIFA WC Creator & RayBan Activation Kick Off",
    date: "2026-03-06",
    time: "5:00 PM",
    duration: "60 min",
    type: "Client",
    clientId: "abi",
    attendees: [dashboardConfig.profile.name, "ABI US Team", "Meta Team"],
    topic: "Kick-off for FIFA World Cup Creator & RayBan activation",
    platform: "NYC 50.48 La Colombe",
    status: "past",
  },

  // ── This week: Mar 9–13, 2026 ──
  {
    id: "m-nmon-1",
    title: "1:1 Bruna",
    date: "2026-03-09",
    time: "9:00 AM",
    duration: "30 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Bruna"],
    topic: "Weekly 1:1 with Bruna",
    platform: "SAO3732.08 Floripa",
    status: "upcoming",
  },
  {
    id: "m-nmon-2",
    title: "Global ABI Core Team Weekly",
    date: "2026-03-09",
    time: "12:30 PM",
    duration: "60 min",
    type: "Client",
    clientId: "abi",
    attendees: [dashboardConfig.profile.name, "ABI Global Core Team"],
    topic: "Global ABI weekly core team sync",
    platform: "SAO3732.08 Floripa",
    status: "upcoming",
  },
  {
    id: "m-nmon-3",
    title: "CS Opex Request Office Hours (Americas & EMEA)",
    date: "2026-03-09",
    time: "1:30 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "CS Team"],
    topic: "Office hours for CS Opex requests",
    platform: "SAO3732.09 Largo da Batata",
    status: "upcoming",
  },
  {
    id: "m-nmon-4",
    title: "1:1 Norah",
    date: "2026-03-09",
    time: "2:00 PM",
    duration: "30 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Norah"],
    topic: "Weekly 1:1 with Norah",
    platform: "Virtual",
    status: "upcoming",
  },
  {
    id: "m-ntue-1",
    title: "Breath Lab - Weekly",
    date: "2026-03-10",
    time: "9:30 AM",
    duration: "30 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Breath Lab Team"],
    topic: "Weekly Breath Lab session",
    platform: "SAO3732.07 Iti Malia",
    status: "upcoming",
  },
  {
    id: "m-ntue-2",
    title: "H1 2026 Business Messaging Product Roadmap Readout",
    date: "2026-03-10",
    time: "1:00 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Business Messaging Team"],
    topic: "H1 2026 Business Messaging product roadmap readout",
    platform: "Virtual",
    status: "upcoming",
  },
  {
    id: "m-ntue-3",
    title: "H1 eCommerce Day: Solutions Live & What's Working Now - LATAM Session",
    date: "2026-03-10",
    time: "2:00 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "eCommerce LATAM Team"],
    topic: "H1 eCommerce Day LATAM session",
    platform: "Virtual",
    status: "upcoming",
  },
  {
    id: "m-ntue-4",
    title: "CS BR Team Meeting",
    date: "2026-03-10",
    time: "4:30 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "CS Brazil Team"],
    topic: "Weekly CS Brazil team meeting",
    platform: "SAO3732.09 Largo da Batata",
    status: "upcoming",
  },
  {
    id: "m-ntue-5",
    title: "Content Council - Meta Festival Creative Edition (Kick-Off)",
    date: "2026-03-10",
    time: "5:00 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Content Council Team"],
    topic: "Kick-off for Meta Festival Creative Edition Content Council",
    platform: "SAO3732.08 Coxinha",
    status: "upcoming",
  },
  {
    id: "m-nthu-1",
    title: "Strategic Weekly Meeting | Netshoes Full Journey at Meta | 2026",
    date: "2026-03-12",
    time: "11:00 AM",
    duration: "60 min",
    type: "Client",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "Netshoes Team"],
    topic: "Strategic weekly meeting for Netshoes full journey at Meta",
    platform: "Virtual",
    status: "upcoming",
  },
  {
    id: "m-nthu-2",
    title: "[ Monthly Sync ] LATAM Team | GEN AI",
    date: "2026-03-12",
    time: "4:15 PM",
    duration: "45 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "LATAM GEN AI Team"],
    topic: "Monthly LATAM GEN AI team sync",
    platform: "SAO3732.09 Largo da Batata",
    status: "upcoming",
  },
  {
    id: "m-nthu-3",
    title: "Strategic Weekly Meeting | O2O Full Journey at Meta | 2026",
    date: "2026-03-12",
    time: "4:30 PM",
    duration: "60 min",
    type: "Internal",
    clientId: null,
    attendees: [dashboardConfig.profile.name, "O2O Team"],
    topic: "Strategic weekly meeting for O2O full journey at Meta",
    platform: "Virtual",
    status: "upcoming",
  },
];

// ─── CLIENT INTERACTIONS (Meta CRM) ─────────────────────────
export const clientInteractions = [
  {
    id: "ci-1",
    clientId: "magalu",
    date: "2026-03-03",
    type: "Creative Workshop",
    title: "A+ Catalog Video — Creative Review",
    summary: "Reviewed first batch of Catalog Product Level Video creatives. Client approved 3 of 5 variants. Next step: scale approved variants across top 50 SKUs.",
    outcome: "Positive",
    nextAction: "Scale approved variants by Mar 10",
    owner: dashboardConfig.profile.name,
  },
  {
    id: "ci-2",
    clientId: "samsung",
    date: "2026-03-02",
    type: "Strategy Call",
    title: "CTX Discovery — Initial Briefing",
    summary: "Presented CTX opportunity to Samsung Brazil team. Strong interest from client. Shared global case studies from Korea and US3. Client requested technical spec sheet.",
    outcome: "Positive",
    nextAction: "Send CTX spec sheet + schedule kickoff",
    owner: dashboardConfig.profile.name,
  },
  {
    id: "ci-3",
    clientId: "amazon",
    date: "2026-02-28",
    type: "Pitch",
    title: "Catalog Video Pitch — Amazon Brazil",
    summary: "Pitched Catalog Product Level Video to Amazon Brazil team. Client showed interest but requested proof-of-concept with 10 ASINs before full commitment. LATAM peer (Mexico) shared positive results.",
    outcome: "Pending",
    nextAction: "Deliver PoC with 10 ASINs by Mar 11",
    owner: dashboardConfig.profile.name,
  },
  {
    id: "ci-4",
    clientId: "abi",
    date: "2026-02-25",
    type: "Creative Sprint",
    title: "Corona Summer 2026 — RFP Response Presentation",
    summary: "Presented Meta's response to Corona 'This is Living' Summer 2026 brief. Proposed Reels Trending Ads + Meta Moment Maker + Partnership Ads ecosystem. Client excited about RTA integration.",
    outcome: "Positive",
    nextAction: "Finalize creative brief + book RTA inventory",
    owner: dashboardConfig.profile.name,
  },
  {
    id: "ci-5",
    clientId: "magalu",
    date: "2026-02-20",
    type: "Strategy Call",
    title: "Partnership Ads — Implementation Check",
    summary: "Checked in on Partnership Ads implementation progress. 3 campaigns live, 2 pending creator approval. Discussed expanding to seasonal campaigns (Easter, Mother's Day).",
    outcome: "On Track",
    nextAction: "Confirm creator approvals by Feb 27",
    owner: dashboardConfig.profile.name,
  },
  {
    id: "ci-6",
    clientId: "samsung",
    date: "2026-02-18",
    type: "Creative Review",
    title: "Galaxy Z Flip — Creator Campaign Review",
    summary: "Reviewed creator content for Galaxy Z Flip campaign. 8 creators submitted content. Selected 5 for Partnership Ads. Discussed Reels placement strategy for Q2.",
    outcome: "Positive",
    nextAction: "Launch Partnership Ads with 5 creators",
    owner: dashboardConfig.profile.name,
  },
  {
    id: "ci-7",
    clientId: "amazon",
    date: "2026-02-14",
    type: "Strategy Call",
    title: "Amazon Afiliados — Creative Strategy",
    summary: "Aligned on creative strategy for Amazon Afiliados program. Discussed creator-led content approach and Reels format adoption. Shared LATAM best practices from Mexico team.",
    outcome: "Positive",
    nextAction: "Develop creator brief for Afiliados",
    owner: dashboardConfig.profile.name,
  },
  {
    id: "ci-8",
    clientId: "abi",
    date: "2026-02-09",
    type: "Workshop",
    title: "Zé Delivery — WhatsApp Creative Lab",
    summary: "Conducted WhatsApp Creative Lab session for Zé Delivery. Explored conversational commerce strategy, AI-powered ordering via WhatsApp. Benchmarked iFood AILO results (+48% conversion).",
    outcome: "Positive",
    nextAction: "Develop MVP proposal for Zé no Zap",
    owner: dashboardConfig.profile.name,
  },
];

// ─── KEY DATES ───────────────────────────────────────────────
export const keyDates = [
  {
    id: "kd-1",
    date: "2026-03-10",
    title: "Magazine Luiza — A+ Catalog Launch",
    type: "Deadline",
    clientId: "magalu",
    description: "Target date to launch Catalog Product Level Video tests across top SKUs",
    priority: "high",
  },
  {
    id: "kd-2",
    date: "2026-03-14",
    title: "Samsung — Creative Diversification Rollout",
    type: "Milestone",
    clientId: "samsung",
    description: "Complete Creative Diversification implementation — $812K combined headroom",
    priority: "high",
  },
  {
    id: "kd-3",
    date: "2026-03-17",
    title: "Q1 Mid-Quarter Review",
    type: "Internal",
    clientId: null,
    description: "Mid-month performance review with all clients + manager sync",
    priority: "medium",
  },
  {
    id: "kd-4",
    date: "2026-03-21",
    title: "Amazon — Partnership Ads Scale",
    type: "Milestone",
    clientId: "amazon",
    description: "Scale Partnership Ads based on February learnings — $453K AR target",
    priority: "high",
  },
  {
    id: "kd-5",
    date: "2026-03-28",
    title: "Q1 Close-Out & Q2 Planning",
    type: "Internal",
    clientId: null,
    description: "Q1 final reporting, results documentation, Q2 priority setting",
    priority: "high",
  },
  {
    id: "kd-6",
    date: "2026-04-01",
    title: "MPK Immersion: Grupo Magalu",
    type: "Event",
    clientId: "magalu",
    description: "Magazine Luiza MPK Immersion — April 2026 canonical document",
    priority: "high",
  },
  {
    id: "kd-7",
    date: "2026-06-01",
    title: "Cannes Lions — AI Creator Pilot",
    type: "Event",
    clientId: null,
    description: "Potential global AI creator community pilot at Cannes Lions (Pedro + Nana initiative)",
    priority: "medium",
  },
  {
    id: "kd-8",
    date: "2026-06-11",
    title: "FIFA World Cup 2026 — Meta+BUD Campaign",
    type: "Campaign",
    clientId: "abi",
    description: "FIFA World Cup 2026 campaign launch — Meta + Budweiser partnership",
    priority: "high",
  },
  {
    id: "kd-9",
    date: "2026-02-28",
    title: "Reels Trending Ads — RS Launch",
    type: "Product",
    clientId: null,
    description: "Reels Trending Ads recommended solution launched in February (already live)",
    priority: "medium",
  },
  {
    id: "kd-10",
    date: "2026-03-24",
    title: "ABI — Creative Diversification Close",
    type: "Deadline",
    clientId: "abi",
    description: "Target: move Creative Diversification from PARTIALLY_ADOPTED → ADOPTED ($752K)",
    priority: "high",
  },
];

// ─── PORTFOLIO SUMMARY ───────────────────────────────────────
export const portfolioSummary = {
  totalClients: 11,
  totalRSes: 126,
  totalARHeadroom: 15600000,
  csEligibleAR: 8100000,
  q1EligibleRSes: 47,
  csEligibility: "100%",
  dedicatedClients: 3,
  topOpportunity: "Magazine Luiza A+ Catalog — $2.5M+",
};

// ─── STAGE COLORS ────────────────────────────────────────────
export const stageConfig: Record<string, { label: string; color: string; bg: string; dot: string }> = {
  DISCOVERY: { label: "Discovery", color: "#6366F1", bg: "#EEF2FF", dot: "#6366F1" },
  PITCHING: { label: "Pitching", color: "#F59E0B", bg: "#FFFBEB", dot: "#F59E0B" },
  SCOPING: { label: "Scoping", color: "#8B5CF6", bg: "#F5F3FF", dot: "#8B5CF6" },
  ACTIONED: { label: "Actioned", color: "#3B82F6", bg: "#EFF6FF", dot: "#3B82F6" },
  PARTIALLY_ADOPTED: { label: "Partial", color: "#F97316", bg: "#FFF7ED", dot: "#F97316" },
  ADOPTED: { label: "Adopted", color: "#10B981", bg: "#ECFDF5", dot: "#10B981" },
  CLOSED: { label: "Closed", color: "#6B7280", bg: "#F9FAFB", dot: "#6B7280" },
  CLOSED_WON: { label: "Won ✓", color: "#059669", bg: "#ECFDF5", dot: "#059669" },
};

export const formatCurrency = (value: number): string => {
  if (value >= 1000000) return `$${(value / 1000000).toFixed(2)}M`;
  if (value >= 1000) return `$${(value / 1000).toFixed(0)}K`;
  return `$${value.toLocaleString()}`;
};

export const formatDate = (dateStr: string): string => {
  const d = new Date(dateStr + "T00:00:00");
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
};

export const getDaysUntil = (dateStr: string): number => {
  // Use Brazil timezone (America/Sao_Paulo) for accurate date comparison
  const todayBRT = new Date().toLocaleDateString("en-CA", { timeZone: "America/Sao_Paulo" }); // YYYY-MM-DD
  const todayMs = new Date(todayBRT + "T00:00:00").getTime();
  const targetMs = new Date(dateStr + "T00:00:00").getTime();
  return Math.ceil((targetMs - todayMs) / (1000 * 60 * 60 * 24));
};
