// ============================================================
// Pedro Menezes — Recommended Solutions Pipeline
// Source: https://www.internalfb.com/crm/pipeline_management
// Filter: Contributors contains Pedro Menezes | Q1 2026 (Current)
// Role: Creative Strategist | View as: Sales
// Scraped: March 6, 2026
// Total: 49 active solutions
// ============================================================

export type RSStage =
  | "Scoped"
  | "Pitched"
  | "Committed"
  | "Actioned"
  | "Partially adopted"
  | "Adopted"
  | "Closed - Lost";

export type RSStatus = "At Risk" | "Overdue" | "On Track" | null;

export interface RecommendedSolution {
  id: string;
  name: string;
  client: "magalu" | "amazon" | "samsung";
  advertiser: string;
  solutionType: string;
  stage: RSStage;
  status: RSStatus;
  eligibleTargetRevenue: number;
  eligibleProgress: number; // percentage 0-100
  attributedRevenue: number;
  attributedProgress: number; // percentage 0-100
  opportunitySize: number;
  revenueStartDate: string;
  revenueEndDate: string;
  lastModified: string;
  lastClientInteraction?: string;
  ciCount?: number;
  owner: string;
  priorityTags?: string[];
}

export const rsPipeline: RecommendedSolution[] = [
  // ── MAGAZINE LUIZA ──
  {
    id: "rs-001",
    name: "Catalog Product Level Video: Creative",
    client: "magalu",
    advertiser: "MAGAZINE LUIZA S/A",
    solutionType: "Catalog Format",
    stage: "Actioned",
    status: "At Risk",
    eligibleTargetRevenue: 5100511,
    eligibleProgress: 9,
    attributedRevenue: 1530153,
    attributedProgress: 9,
    opportunitySize: 1530153,
    revenueStartDate: "2026-01-09",
    revenueEndDate: "2026-04-09",
    lastModified: "2026-02-24",
    lastClientInteraction: "2026-02-10",
    ciCount: 3,
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-002",
    name: "Catalog Product Level Video: Creative",
    client: "magalu",
    advertiser: "NS2.COM INTERNET S.A.",
    solutionType: "Catalog ad format",
    stage: "Actioned",
    status: null,
    eligibleTargetRevenue: 1597939,
    eligibleProgress: 3,
    attributedRevenue: 479381,
    attributedProgress: 0,
    opportunitySize: 479381,
    revenueStartDate: "2025-11-05",
    revenueEndDate: "2026-02-03",
    lastModified: "2026-02-03",
    lastClientInteraction: "2026-01-08",
    ciCount: 14,
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-003",
    name: "Catalog Product Level Video: Creative",
    client: "magalu",
    advertiser: "NS2.COM INTERNET S.A.",
    solutionType: "Catalog ad format",
    stage: "Actioned",
    status: null,
    eligibleTargetRevenue: 1559083,
    eligibleProgress: 4,
    attributedRevenue: 467724,
    attributedProgress: 0,
    opportunitySize: 467724,
    revenueStartDate: "2025-11-05",
    revenueEndDate: "2026-02-03",
    lastModified: "2026-02-24",
    lastClientInteraction: "2025-12-17",
    ciCount: 8,
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-004",
    name: "Scale partnership ads in more campaigns",
    client: "magalu",
    advertiser: "MAGAZINE LUIZA S/A",
    solutionType: "Partnership ads",
    stage: "Actioned",
    status: null,
    eligibleTargetRevenue: 3603501,
    eligibleProgress: 3,
    attributedRevenue: 384721,
    attributedProgress: 2,
    opportunitySize: 384721,
    revenueStartDate: "2025-11-24",
    revenueEndDate: "2026-02-22",
    lastModified: "2026-02-24",
    lastClientInteraction: "2026-02-10",
    ciCount: 11,
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-005",
    name: "Creative: Increase Creative Diversification",
    client: "magalu",
    advertiser: "MAGAZINE LUIZA S/A",
    solutionType: "Advantage+ creative",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 564387,
    eligibleProgress: 32,
    attributedRevenue: 75641,
    attributedProgress: 26,
    opportunitySize: 75641,
    revenueStartDate: "2025-11-05",
    revenueEndDate: "2026-02-03",
    lastModified: "2026-02-24",
    lastClientInteraction: "2026-02-10",
    ciCount: 8,
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-006",
    name: "Catalog Product Level Video: Creative",
    client: "magalu",
    advertiser: "MAGAZINE LUIZA S/A",
    solutionType: "Catalog ad format",
    stage: "Adopted",
    status: null,
    eligibleTargetRevenue: 464525,
    eligibleProgress: 100,
    attributedRevenue: 139357,
    attributedProgress: 100,
    opportunitySize: 139357,
    revenueStartDate: "2025-11-05",
    revenueEndDate: "2026-02-03",
    lastModified: "2026-02-20",
    lastClientInteraction: "2026-01-29",
    ciCount: 10,
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-007",
    name: "Scale partnership ads in more campaigns",
    client: "magalu",
    advertiser: "NS2.COM INTERNET S.A.",
    solutionType: "Partnership ads",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 270580,
    eligibleProgress: 10,
    attributedRevenue: 28952,
    attributedProgress: 0,
    opportunitySize: 28952,
    revenueStartDate: "2025-11-05",
    revenueEndDate: "2026-02-03",
    lastModified: "2026-02-24",
    lastClientInteraction: "2026-02-10",
    ciCount: 8,
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-008",
    name: "Opt into Reels placements using 9:16 video with audio",
    client: "magalu",
    advertiser: "Epoca Cosmeticos",
    solutionType: "Reels performant creative",
    stage: "Scoped",
    status: null,
    eligibleTargetRevenue: 623056,
    eligibleProgress: 0,
    attributedRevenue: 27738,
    attributedProgress: 0,
    opportunitySize: 27738,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-009",
    name: "Test promo ads (Highlight your promotions)",
    client: "magalu",
    advertiser: "NS2.COM INTERNET S.A.",
    solutionType: "Promo Ads",
    stage: "Actioned",
    status: null,
    eligibleTargetRevenue: 527747,
    eligibleProgress: 1,
    attributedRevenue: 24276,
    attributedProgress: 0,
    opportunitySize: 24276,
    revenueStartDate: "2025-11-05",
    revenueEndDate: "2026-02-03",
    lastModified: "2026-02-24",
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-010",
    name: "Catalog Format, Gen AI Creative REELS VILLA",
    client: "magalu",
    advertiser: "MAGAZINE LUIZA S/A",
    solutionType: "Gen AI Creative / Catalog Format",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 1000000,
    eligibleProgress: 12,
    attributedRevenue: 23137,
    attributedProgress: 11,
    opportunitySize: 23137,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-011",
    name: "Opt into Reels placements using 9:16 video with audio",
    client: "magalu",
    advertiser: "MAGAZINE LUIZA S/A",
    solutionType: "Reels",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 432226,
    eligibleProgress: 44,
    attributedRevenue: 14015,
    attributedProgress: 60,
    opportunitySize: 14015,
    revenueStartDate: "2025-11-05",
    revenueEndDate: "2026-02-03",
    lastModified: "2026-02-24",
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-012",
    name: "Catalog Product Level Video: Creative",
    client: "magalu",
    advertiser: "KABUM COMERCIO ELETRONICO S.A.",
    solutionType: "Catalog ad format",
    stage: "Actioned",
    status: "At Risk",
    eligibleTargetRevenue: 369444,
    eligibleProgress: 7,
    attributedRevenue: 110833,
    attributedProgress: 0,
    opportunitySize: 110833,
    revenueStartDate: "2026-01-09",
    revenueEndDate: "2026-04-09",
    lastModified: "2026-02-24",
    owner: "Thelio Goncalves",
  },
  {
    id: "rs-013",
    name: "Catalog Product Level Video: Creative",
    client: "magalu",
    advertiser: "MAGAZINE LUIZA S/A",
    solutionType: "Catalog Format",
    stage: "Scoped",
    status: null,
    eligibleTargetRevenue: 191678,
    eligibleProgress: 0,
    attributedRevenue: 57503,
    attributedProgress: 0,
    opportunitySize: 57503,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Thelio Goncalves",
  },

  // ── AMAZON ──
  {
    id: "rs-014",
    name: "Catalog Product Level Video: Creative",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Catalog Format",
    stage: "Actioned",
    status: null,
    eligibleTargetRevenue: 3356257,
    eligibleProgress: 4,
    attributedRevenue: 1006877,
    attributedProgress: 4,
    opportunitySize: 1006877,
    revenueStartDate: "2026-02-09",
    revenueEndDate: "2026-05-09",
    lastModified: "2026-03-05",
    lastClientInteraction: "2026-02-27",
    ciCount: 7,
    owner: "Douglas Mendes",
  },
  {
    id: "rs-015",
    name: "Scale partnership ads in more campaigns",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Partnership ads",
    stage: "Actioned",
    status: "At Risk",
    eligibleTargetRevenue: 5875129,
    eligibleProgress: 4,
    attributedRevenue: 613837,
    attributedProgress: 0,
    opportunitySize: 613837,
    revenueStartDate: "2025-12-16",
    revenueEndDate: "2026-03-16",
    lastModified: "2026-02-24",
    lastClientInteraction: "2026-02-10",
    ciCount: 18,
    owner: "Douglas Mendes",
  },
  {
    id: "rs-016",
    name: "Add Advantage+ campaign budget",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Advantage+ campaign budget",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 6514889,
    eligibleProgress: 16,
    attributedRevenue: 325744,
    attributedProgress: 16,
    opportunitySize: 325744,
    revenueStartDate: "2025-11-21",
    revenueEndDate: "2026-02-19",
    lastModified: "2026-02-28",
    lastClientInteraction: "2026-02-27",
    ciCount: 6,
    owner: "Douglas Mendes",
  },
  {
    id: "rs-017",
    name: "Simplify or consolidate ad sets",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Account simplification",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 2055228,
    eligibleProgress: 66,
    attributedRevenue: 312394,
    attributedProgress: 66,
    opportunitySize: 312394,
    revenueStartDate: "2025-11-13",
    revenueEndDate: "2026-02-11",
    lastModified: "2026-02-28",
    lastClientInteraction: "2026-02-27",
    ciCount: 8,
    owner: "Douglas Mendes",
  },
  {
    id: "rs-018",
    name: "Catalog Product Level Video: Creative",
    client: "amazon",
    advertiser: "Audible Mexico",
    solutionType: "Catalog ad format",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 852570,
    eligibleProgress: 58,
    attributedRevenue: 255771,
    attributedProgress: 51,
    opportunitySize: 255771,
    revenueStartDate: "2025-11-23",
    revenueEndDate: "2026-02-20",
    lastModified: "2026-02-20",
    lastClientInteraction: "2026-01-29",
    ciCount: 10,
    owner: "Douglas Mendes",
  },
  {
    id: "rs-019",
    name: "Catalog Product Level Video: Creative",
    client: "amazon",
    advertiser: "Audible Brazil",
    solutionType: "Catalog Format",
    stage: "Actioned",
    status: "At Risk",
    eligibleTargetRevenue: 648202,
    eligibleProgress: 6,
    attributedRevenue: 194460,
    attributedProgress: 6,
    opportunitySize: 194460,
    revenueStartDate: "2026-01-19",
    revenueEndDate: "2026-04-19",
    lastModified: "2026-02-24",
    lastClientInteraction: "2026-01-28",
    ciCount: 3,
    owner: "Douglas Mendes",
  },
  {
    id: "rs-020",
    name: "Advantage+ audience",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Audience expansion",
    stage: "Actioned",
    status: null,
    eligibleTargetRevenue: 1892687,
    eligibleProgress: 1,
    attributedRevenue: 123024,
    attributedProgress: 1,
    opportunitySize: 123024,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-021",
    name: "Opt into Reels placements using 9:16 video with audio",
    client: "amazon",
    advertiser: "Audible Brazil",
    solutionType: "Reels",
    stage: "Actioned",
    status: null,
    priorityTags: ["Whales"],
    eligibleTargetRevenue: 1402737,
    eligibleProgress: 5,
    attributedRevenue: 62578,
    attributedProgress: 0,
    opportunitySize: 62578,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-022",
    name: "Opt into Reels placements using 9:16 video with audio",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Reels performant creative",
    stage: "Actioned",
    status: "At Risk",
    eligibleTargetRevenue: 1018853,
    eligibleProgress: 19,
    attributedRevenue: 50260,
    attributedProgress: 29,
    opportunitySize: 50260,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-023",
    name: "Enable Advantage+ creative enhancements",
    client: "amazon",
    advertiser: "Audible Mexico",
    solutionType: "Advantage+ creative",
    stage: "Committed",
    status: null,
    eligibleTargetRevenue: 796699,
    eligibleProgress: 0,
    attributedRevenue: 32585,
    attributedProgress: 0,
    opportunitySize: 32585,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-024",
    name: "Creative: Increase Creative Diversification",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Advantage+ creative / Creative Diversification",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 280267,
    eligibleProgress: 36,
    attributedRevenue: 31247,
    attributedProgress: 25,
    opportunitySize: 31247,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-025",
    name: "Enable Advantage+ creative enhancements",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Advantage+ creative",
    stage: "Pitched",
    status: null,
    eligibleTargetRevenue: 543323,
    eligibleProgress: 0,
    attributedRevenue: 22221,
    attributedProgress: 0,
    opportunitySize: 22221,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-026",
    name: "Creative: Increase Creative Diversification",
    client: "amazon",
    advertiser: "Audible Mexico",
    solutionType: "Advantage+ creative / Creative Diversification",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 171529,
    eligibleProgress: 96,
    attributedRevenue: 18293,
    attributedProgress: 94,
    opportunitySize: 18293,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-027",
    name: "Adopt Advantage+ end-to-end campaigns",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Advantage+ sales campaign",
    stage: "Actioned",
    status: null,
    eligibleTargetRevenue: 1615551,
    eligibleProgress: 9,
    attributedRevenue: 91473,
    attributedProgress: 0,
    opportunitySize: 91473,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-028",
    name: "Opt into Reels placements using 9:16 video with audio",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Reels performant creative",
    stage: "Actioned",
    status: "At Risk",
    eligibleTargetRevenue: 2605954,
    eligibleProgress: 1,
    attributedRevenue: 67193,
    attributedProgress: 1,
    opportunitySize: 67193,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-029",
    name: "Product Extensions",
    client: "amazon",
    advertiser: "AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.",
    solutionType: "Catalog ad format",
    stage: "Partially adopted",
    status: null,
    eligibleTargetRevenue: 647933,
    eligibleProgress: 0,
    attributedRevenue: 66737,
    attributedProgress: 0,
    opportunitySize: 66737,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },
  {
    id: "rs-030",
    name: "Audible BF - MX",
    client: "amazon",
    advertiser: "Audible Mexico",
    solutionType: "Audience expansion / Partnership ads / Creative Diversification",
    stage: "Adopted",
    status: null,
    eligibleTargetRevenue: 900000,
    eligibleProgress: 0,
    attributedRevenue: 11386,
    attributedProgress: 0,
    opportunitySize: 11386,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Douglas Mendes",
  },

  // ── SAMSUNG ──
  {
    id: "rs-031",
    name: "Adopt CTX",
    client: "samsung",
    advertiser: "Samsung Electronics Co Ltd - KR(USD)",
    solutionType: "Click to message (CTX)",
    stage: "Actioned",
    status: "Overdue",
    eligibleTargetRevenue: 3236508,
    eligibleProgress: 0,
    attributedRevenue: 970952,
    attributedProgress: 0,
    opportunitySize: 970952,
    revenueStartDate: "2026-03-19",
    revenueEndDate: "2026-06-17",
    lastModified: "2026-03-05",
    owner: "Bruno Boehringer Mastantuono",
  },
  {
    id: "rs-032",
    name: "Scale partnership ads in more campaigns",
    client: "samsung",
    advertiser: "Samsung Electronics Co Ltd - KR(USD)",
    solutionType: "Partnership ads",
    stage: "Actioned",
    status: null,
    eligibleTargetRevenue: 5312148,
    eligibleProgress: 2,
    attributedRevenue: 567608,
    attributedProgress: 0,
    opportunitySize: 567608,
    revenueStartDate: "2025-11-06",
    revenueEndDate: "2026-02-04",
    lastModified: "2026-02-26",
    lastClientInteraction: "2026-02-25",
    ciCount: 8,
    owner: "Bruno Boehringer Mastantuono",
  },
  {
    id: "rs-033",
    name: "Creative: Increase Creative Diversification",
    client: "samsung",
    advertiser: "Samsung Electronics Co Ltd - KR(USD)",
    solutionType: "Advantage+ creative",
    stage: "Actioned",
    status: "At Risk",
    eligibleTargetRevenue: 3430413,
    eligibleProgress: 6,
    attributedRevenue: 487105,
    attributedProgress: 0,
    opportunitySize: 487105,
    revenueStartDate: "2025-12-16",
    revenueEndDate: "2026-03-16",
    lastModified: "2026-03-05",
    lastClientInteraction: "2026-02-25",
    ciCount: 10,
    owner: "Bruno Boehringer Mastantuono",
  },
  {
    id: "rs-034",
    name: "Creative: Increase Creative Diversification",
    client: "samsung",
    advertiser: "Samsung Electronics Co Ltd - KR(USD)",
    solutionType: "Advantage+ creative / Creative Diversification",
    stage: "Actioned",
    status: "At Risk",
    eligibleTargetRevenue: 3560532,
    eligibleProgress: 1,
    attributedRevenue: 478529,
    attributedProgress: 1,
    opportunitySize: 478529,
    revenueStartDate: "2026-01-18",
    revenueEndDate: "2026-04-18",
    lastModified: "2026-03-05",
    lastClientInteraction: "2026-01-14",
    ciCount: 1,
    owner: "Bruno Boehringer Mastantuono",
    priorityTags: ["Creative Diversification"],
  },
  {
    id: "rs-035",
    name: "Adopt CTX",
    client: "samsung",
    advertiser: "Samsung Electronics Co Ltd - KR(USD)",
    solutionType: "Click to message (CTX)",
    stage: "Actioned",
    status: null,
    eligibleTargetRevenue: 1625733,
    eligibleProgress: 4,
    attributedRevenue: 125523,
    attributedProgress: 10,
    opportunitySize: 125523,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-03-05",
    owner: "Bruno Boehringer Mastantuono",
  },
  {
    id: "rs-036",
    name: "Opt into Reels placements using 9:16 video with audio",
    client: "samsung",
    advertiser: "Samsung Electronics Co Ltd - KR(USD)",
    solutionType: "Reels",
    stage: "Pitched",
    status: "Overdue",
    eligibleTargetRevenue: 2484898,
    eligibleProgress: 0,
    attributedRevenue: 118305,
    attributedProgress: 0,
    opportunitySize: 118305,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Bruno Boehringer Mastantuono",
  },
  {
    id: "rs-037",
    name: "Scale partnership ads in more campaigns",
    client: "samsung",
    advertiser: "Samsung Electronics Co Ltd - KR(USD)",
    solutionType: "Partnership ads",
    stage: "Actioned",
    status: "At Risk",
    eligibleTargetRevenue: 2056073,
    eligibleProgress: 0,
    attributedRevenue: 99568,
    attributedProgress: 0,
    opportunitySize: 99568,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Bruno Boehringer Mastantuono",
  },
  {
    id: "rs-038",
    name: "Creative: Increase Creative Diversification",
    client: "samsung",
    advertiser: "Samsung Electronics Co Ltd - KR(USD)",
    solutionType: "Advantage+ creative",
    stage: "Adopted",
    status: null,
    eligibleTargetRevenue: 601407,
    eligibleProgress: 100,
    attributedRevenue: 86365,
    attributedProgress: 100,
    opportunitySize: 86365,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Bruno Boehringer Mastantuono",
  },
  {
    id: "rs-039",
    name: "Opt into Reels placements using 9:16 video with audio",
    client: "samsung",
    advertiser: "Samsung Electronics Co Ltd - KR(USD)",
    solutionType: "Reels",
    stage: "Adopted",
    status: null,
    eligibleTargetRevenue: 1226667,
    eligibleProgress: 100,
    attributedRevenue: 51558,
    attributedProgress: 100,
    opportunitySize: 51558,
    revenueStartDate: "2026-01-01",
    revenueEndDate: "2026-03-31",
    lastModified: "2026-02-24",
    owner: "Bruno Boehringer Mastantuono",
  },
];

// ── Portfolio Summary ──
export const rsSummary = {
  total: 49,
  totalOpportunitySize: 9679306,
  totalEligibleTargetRevenue: 72194968,
  eligibleProgress: 13, // 13% — $9,521,681/$72,194,968
  attributedProgress: 10, // 10% — $1,043,548/$9,679,306
  stageBreakdown: {
    Scoped: 3,
    Pitched: 5,
    Committed: 2,
    Actioned: 19,
    "Partially adopted": 12,
    Adopted: 5,
    "Closed - Lost": 0,
  },
  dataAsOf: "2026-03-06",
  sourceUrl:
    "https://www.internalfb.com/crm/pipeline_management?use_as=1084877300&pipeline_management_tab=YOUR_SOLUTIONS&solution_table_status_tab=ACTIVE&metacrm_tool=pipeline_management&period=CURRENT_QUARTER&commission_split_role_name=CREATIVE_STRATEGIST",
};

// ── Stage config ──
export const rsStageConfig: Record<RSStage, { label: string; bg: string; color: string; dot: string }> = {
  Scoped:             { label: "Scoped",           bg: "#F3F4F6", color: "#374151", dot: "#9CA3AF" },
  Pitched:            { label: "Pitched",          bg: "#EFF6FF", color: "#1D4ED8", dot: "#3B82F6" },
  Committed:          { label: "Committed",        bg: "#F0FDF4", color: "#166534", dot: "#22C55E" },
  Actioned:           { label: "Actioned",         bg: "#ECFDF5", color: "#065F46", dot: "#10B981" },
  "Partially adopted":{ label: "Partial",          bg: "#FFFBEB", color: "#92400E", dot: "#F59E0B" },
  Adopted:            { label: "Adopted",          bg: "#F0FDF4", color: "#14532D", dot: "#16A34A" },
  "Closed - Lost":    { label: "Closed",           bg: "#FEF2F2", color: "#991B1B", dot: "#EF4444" },
};

export const rsStatusConfig: Record<string, { bg: string; color: string; label: string }> = {
  "At Risk": { bg: "#FEF3C7", color: "#92400E", label: "At Risk" },
  "Overdue": { bg: "#FEE2E2", color: "#991B1B", label: "Overdue" },
  "On Track": { bg: "#DCFCE7", color: "#166534", label: "On Track" },
};

// Client color map
export const rsClientColors: Record<string, { color: string; light: string; name: string }> = {
  magalu:  { color: "#EC4899", light: "#FCE7F3", name: "Magalu" },
  amazon:  { color: "#F59E0B", light: "#FEF3C7", name: "Amazon" },
  samsung: { color: "#3B82F6", light: "#EFF6FF", name: "Samsung" },
};

// ── AR Headroom by Client ─────────────────────────────────────
// Source: CRM Scorecard (internalfb.com/crm/guidance_home?currentTab=SCORECARD)
// Filter: Your BoB · Current Quarter · Granularity: Organization
// Scraped by Manus during setup and daily refresh.
export interface ClientARData {
  clientId: string;       // matches dashboardConfig.clients[].id
  clientName: string;     // Ultimate Parent name from CRM Scorecard
  totalAR: number;        // AR Headroom (total, in USD)
  csEligibleAR: number;   // CS-Eligible AR (in USD)
}

export const clientARData: ClientARData[] = [
  { clientId: "magalu",  clientName: "Magazine Luiza",  totalAR: 7200000, csEligibleAR: 3800000 },
  { clientId: "amazon",  clientName: "Amazon",          totalAR: 5100000, csEligibleAR: 2700000 },
  { clientId: "samsung", clientName: "Samsung",         totalAR: 3300000, csEligibleAR: 1600000 },
];

export const portfolioARSummary = {
  totalARHeadroom: clientARData.reduce((s, c) => s + c.totalAR, 0),
  csEligibleAR: clientARData.reduce((s, c) => s + c.csEligibleAR, 0),
  topOpportunity: clientARData.length > 0
    ? `${clientARData[0].clientName} — $${(clientARData[0].totalAR / 1_000_000).toFixed(1)}M AR`
    : "—",
  dataAsOf: "2026-03-06",
  sourceUrl: "https://www.internalfb.com/crm/guidance_home?currentTab=SCORECARD&granularity=ORGANIZATION&guidanceType=PERFORMANCE_FIVE",
};
