// ============================================================
// Creative Shop Dashboard — Setup Wizard
// A multi-step onboarding form for new CS peers to configure
// their personal dashboard without editing code directly.
// ============================================================

import { useState, useEffect, useRef } from "react";
import { CheckCircle, ChevronRight, ChevronLeft, User, BarChart2, Globe, Users, Palette, Copy, Check, Loader2, Sparkles, MessageSquare, ExternalLink, ArrowRight, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { CS_AMERICAS_NAMES, CS_AMERICAS_MANAGERS, getManagerForPerson, getTeamForPerson } from "@shared/csOrgData";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";

// ── Step definitions ──────────────────────────────────────────
const STEPS = [
  { id: 1, title: "Your Identity", icon: User, description: "Name, role, and team details" },
  { id: 2, title: "Unidash Filters", icon: BarChart2, description: "CI and AI Usage data filters" },
  { id: 3, title: "Client Portfolio", icon: Users, description: "Your dedicated clients" },
  { id: 4, title: "Appearance", icon: Palette, description: "Colors and greeting language" },
];

type WorkplaceGroup = { name: string; url: string; description: string };
type Client = { id: string; name: string; shortName: string; tier: string; color: string; summary: string };

interface WizardData {
  // Step 1 — Identity
  name: string;
  firstName: string;
  role: string;
  team: string;
  territory: string;
  manager: string;
  initials: string;
  avatarColor: string;
  profileUrl: string;
  fbid: string;
  isInOffice: boolean;
  // Step 2 — Unidash
  salesRepName: string;
  quarter: string;
  ciMinTarget: string;
  crmCiUrl: string;
  // Step 3 — Clients
  clients: Client[];
  // Step 4 — Appearance
  greeting: string;
  primaryColor: string;
  timezone: string;
  dailyRefreshTime: string;
}

const DEFAULT_DATA: WizardData = {
  name: "",
  firstName: "",
  role: "Creative Strategist",
  team: "Creative Shop LATAM",
  territory: "Brazil (GBG-LATAM)",
  manager: "",
  initials: "",
  avatarColor: "#7C3AED",
  profileUrl: "",
  fbid: "",
  isInOffice: true,
  salesRepName: "",
  quarter: "Q1 2026",
  ciMinTarget: "3",
  crmCiUrl: "",
  clients: [{ id: "", name: "", shortName: "", tier: "A", color: "#0064E0", summary: "" }],
  greeting: "Good morning",
  primaryColor: "#7C3AED",
  timezone: "America/Sao_Paulo",
  dailyRefreshTime: "07:00",
};

// ── Config generator ──────────────────────────────────────────
function generateConfig(data: WizardData): string {
  const clients = data.clients
    .filter((c) => c.name.trim())
    .map(
      (c) => `    {
      id: "${c.id || c.name.toLowerCase().replace(/\s+/g, "-")}",
      name: "${c.name}",
      shortName: "${c.shortName || c.name}",
      tier: "${c.tier}",
      color: "${c.color}",
      lightColor: "#F5F5FF",
      logo: "🏢",
      summary: "${c.summary}",
    }`
    )
    .join(",\n");

  return `// ============================================================
// 🎨 Creative Shop Dashboard — Personal Configuration
// Generated by Setup Wizard on ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
// ============================================================

export const dashboardConfig = {
  profile: {
    name: "${data.name}",
    firstName: "${data.firstName || data.name.split(" ")[0]}",
    role: "${data.role}",
    team: "${data.team}",
    company: "Meta",
    territory: "${data.territory}",
    manager: "${data.manager}",
    initials: "${data.initials || (data.name.split(" ").map((n) => n[0]).join("").slice(0, 2).toUpperCase())}",
    avatarColor: "${data.avatarColor}",
    isInOffice: ${data.isInOffice},
  },

  unidash: {
    salesRepName: "${data.salesRepName || data.name}",
    quarter: "${data.quarter}",
    ciMinTarget: ${parseInt(data.ciMinTarget) || 3},
    ciUrl: "https://www.internalfb.com/unidash/dashboard/engagement_management_process_dashboard/dcmp_client_interaction_insights/",
    aiUsageUrl: "https://www.internalfb.com/unidash/dashboard/ai_usage_at_meta/ai4p_by_pillar/my_ai_usage",
  },

  crm: {
    // CI filter: Participant is in my BoB + This Quarter + Is qualified + Participant contains any of [Your Name]
    // Auto-generated from your internal FBID — do not edit manually
    ciUrl: "${data.fbid
      ? `https://www.internalfb.com/crm/client_interactions?view=list&filters=[{%22field%22:%22participant%22,%22operator%22:%22fbid_set_participant_in_book_of_business%22,%22value%22:{%22type%22:%22empty%22}},{%22field%22:%22interaction_time%22,%22operator%22:%22timestamp_in_range_within_this_quarter%22,%22value%22:{%22type%22:%22empty%22}},{%22field%22:%22is_qualified%22,%22operator%22:%22bool_is_true%22,%22value%22:{%22type%22:%22empty%22}},{%22field%22:%22participant%22,%22operator%22:%22fbid_set_contains_any_of%22,%22value%22:{%22type%22:%22fbid_list%22,%22fbid_list%22:[%22${data.fbid}%22]}}]&direction=descending&sortKey=INTERACTION_TIME`
      : data.crmCiUrl || 'https://www.internalfb.com/crm/client_interactions'}",
    fbid: "${data.fbid}",
  },

  workplace: {
    primaryGroup: {
      name: "CS: The Work",
      url: "https://fb.workplace.com/groups/365231093525512",
    },
    groups: [],
    scrapeFeed: false,
    feedUrl: "https://fb.workplace.com",
  },

  calendarUrl: "https://www.internalfb.com/calendar",

  appearance: {
    sidebarAccentColor: "#1a1f36",
    primaryColor: "${data.primaryColor}",
    secondaryColor: "#0064E0",
    greeting: "${data.greeting}",
  },

  schedule: {
    dailyRefreshTime: "${data.dailyRefreshTime}",
    timezone: "${data.timezone}",
  },

  clients: [
${clients}
  ],
};

export type DashboardConfig = typeof dashboardConfig;
`;
}

// ── Step components ───────────────────────────────────────────

/** Fetch state for the optional "Fetch Profile Data" button */
type FetchState =
  | { phase: "idle" }
  | { phase: "requesting" }
  | { phase: "waiting"; requestId: number }
  | { phase: "fulfilled" }
  | { phase: "timed_out" }
  | { phase: "error"; message: string };

const POLL_INTERVAL_MS = 5_000;
const POLL_TIMEOUT_MS = 60_000;

function StepIdentity({ data, onChange }: { data: WizardData; onChange: (d: Partial<WizardData>) => void }) {
  // ── Autocomplete state ────────────────────────────────────
  const [nameOpen, setNameOpen] = useState(false);
  const [managerOpen, setManagerOpen] = useState(false);

  const handleNameSelect = (selectedName: string) => {
    const firstName = selectedName.split(" ")[0] ?? "";
    const initials = selectedName.split(" ").filter(Boolean).map((n) => n[0]).join("").slice(0, 2).toUpperCase();
    const autoManager = getManagerForPerson(selectedName);
    const autoTeam = getTeamForPerson(selectedName);
    onChange({
      name: selectedName,
      firstName,
      initials,
      salesRepName: selectedName,
      ...(autoManager ? { manager: autoManager } : {}),
      ...(autoTeam ? { team: autoTeam } : {}),
    });
    setNameOpen(false);
  };

  const handleManagerSelect = (selectedManager: string) => {
    onChange({ manager: selectedManager });
    setManagerOpen(false);
  };

  // tRPC mutations & queries
  const requestToBeAddedMutation = trpc.profileFetch.requestToBeAdded.useMutation();
  const [addRequested, setAddRequested] = useState(false);

  const handleRequestToBeAdded = async () => {
    if (!data.name.trim()) return;
    try {
      await requestToBeAddedMutation.mutateAsync({ name: data.name.trim() });
      setAddRequested(true);
      toast.success("Request sent!", {
        description: `Pedro will add "${data.name}" to the CS Americas list. Fill the fields manually for now.`,
        duration: 6000,
      });
    } catch {
      toast.error("Couldn't send request", { description: "Fill the fields manually." });
    }
  };

  // Derive display values in real time
  const displayInitials = data.initials ||
    data.name.split(" ").filter(Boolean).map((n) => n[0]).join("").slice(0, 2).toUpperCase() ||
    "?";
  const displayName = data.name || "Your Name";
  const displayRole = data.role || "Creative Strategist";
  const displayTeam = data.team || "Creative Shop";

  return (
    <div className="space-y-4">
      {/* Live avatar preview */}
      <div className="rounded-xl border border-purple-100 bg-gradient-to-br from-[#1a1f36] to-[#2d3561] p-4 flex items-center gap-4">
        <div
          className="w-14 h-14 rounded-full flex items-center justify-center text-lg font-bold text-white flex-shrink-0 shadow-lg transition-all duration-300"
          style={{ background: data.avatarColor || "#7C3AED" }}
        >
          {displayInitials}
        </div>
        <div className="min-w-0">
          <p className="text-white font-semibold text-sm truncate">{displayName}</p>
          <p className="text-purple-300 text-xs truncate">{displayRole}</p>
          <p className="text-gray-400 text-xs truncate mt-0.5">{displayTeam}</p>
        </div>
        <div className="ml-auto text-xs text-gray-500 italic shrink-0">Live preview</div>
      </div>

      {/* Profile cross-check guide */}
      <div className="bg-green-50 border border-green-200 rounded-lg p-4 text-sm text-green-800 space-y-2">
        <p>
          <strong>Start by typing your name below</strong> — if you're in CS Americas, it will auto-fill your Manager and Team. Then fill in the remaining fields and paste your profile URL at the bottom to enable the CRM CI filter.
        </p>
        <div className="grid grid-cols-2 gap-x-6 gap-y-1 text-green-700 text-xs mt-1">
          <div><span className="font-semibold">Full Name</span> → headline name on your profile card</div>
          <div><span className="font-semibold">Job Title</span> → shown below your name (e.g. "Creative Strategist")</div>
          <div><span className="font-semibold">Team</span> → "Workday team" field (e.g. "GP - Creative Shop Americas - LATAM")</div>
          <div><span className="font-semibold">Manager</span> → "Reports to" field on your profile card</div>
        </div>
        <p className="text-green-600 text-xs italic">
          Not in CS Americas? Fill the fields manually using your{" "}
          <a href="https://www.internalfb.com/profile/view" target="_blank" rel="noreferrer" className="underline">internal profile page</a> as reference.
        </p>
      </div>

      {/* ── Fields grid ──────────────────────────────────────────── */}
      <div className="grid grid-cols-2 gap-4">
          {/* Full Name — autocomplete */}
          <div className="col-span-2">
            <div className="flex items-center gap-2">
              <Label htmlFor="name">Full Name <span className="text-red-500">*</span></Label>
              <span className="text-xs bg-blue-50 text-blue-600 border border-blue-200 rounded px-1.5 py-0.5 font-medium">CS Americas only</span>
            </div>
            <div className="relative mt-1">
              <Input
                id="name"
                value={data.name}
                onChange={(e) => {
                  onChange({ name: e.target.value, salesRepName: e.target.value });
                  setNameOpen(e.target.value.length >= 2);
                }}
                onFocus={() => { if (data.name.length >= 2) setNameOpen(true); }}
                onBlur={() => setTimeout(() => setNameOpen(false), 150)}
                placeholder="Ana Lima"
                autoComplete="off"
              />
              {nameOpen && data.name.length >= 2 && (() => {
                const matches = CS_AMERICAS_NAMES.filter((n) =>
                  n.toLowerCase().includes(data.name.toLowerCase())
                );
                if (matches.length === 0) return null;
                return (
                  <div className="absolute z-50 mt-1 w-full max-h-60 overflow-y-auto rounded-md border border-gray-200 bg-white shadow-lg">
                    <div className="px-3 py-1.5 text-xs font-semibold text-gray-500 uppercase tracking-wide border-b border-gray-100">CS Americas</div>
                    {matches.map((n) => (
                      <button
                        key={n}
                        type="button"
                        className="w-full text-left px-3 py-2 text-sm hover:bg-purple-50 hover:text-purple-700 transition-colors"
                        onMouseDown={(e) => { e.preventDefault(); handleNameSelect(n); }}
                      >
                        {n}
                      </button>
                    ))}
                  </div>
                );
              })()}
            </div>
            <p className="text-xs text-gray-500 mt-1">Must match exactly how your name appears in Unidash's "Sales Rep" filter. Selecting from the list auto-fills Manager and Team.</p>
            {data.name.length >= 2 && !CS_AMERICAS_NAMES.some((n) => n.toLowerCase() === data.name.toLowerCase()) && (
              <p className="text-xs mt-1">
                {addRequested ? (
                  <span className="text-green-600">✓ Request sent — Pedro will add you to the list soon. Fill the fields manually for now.</span>
                ) : (
                  <span className="text-gray-500">
                    Not in CS Americas?{" "}
                    <button
                      type="button"
                      onClick={handleRequestToBeAdded}
                      disabled={requestToBeAddedMutation.isPending}
                      className="text-purple-600 underline hover:text-purple-800 disabled:opacity-50"
                    >
                      {requestToBeAddedMutation.isPending ? "Sending…" : "Request to be added"}
                    </button>
                    {" "}or fill the fields manually below.
                  </span>
                )}
              </p>
            )}
          </div>
          <div>
            <Label htmlFor="firstName">First Name</Label>
            <Input id="firstName" value={data.firstName} onChange={(e) => onChange({ firstName: e.target.value })} placeholder="Ana" className="mt-1" />
          </div>
          <div>
            <Label htmlFor="initials">Initials</Label>
            <Input id="initials" value={data.initials} onChange={(e) => onChange({ initials: e.target.value.toUpperCase().slice(0, 2) })} placeholder="AL" maxLength={2} className="mt-1" />
          </div>
          <div>
            <Label htmlFor="role">Job Title</Label>
            <Input id="role" value={data.role} onChange={(e) => onChange({ role: e.target.value })} placeholder="Creative Strategist" className="mt-1" />
          </div>
          <div>
            <Label htmlFor="team">Team</Label>
            <Input id="team" value={data.team} onChange={(e) => onChange({ team: e.target.value })} placeholder="Creative Shop LATAM" className="mt-1" />
          </div>
          <div>
            <Label htmlFor="territory">Territory</Label>
            <Input id="territory" value={data.territory} onChange={(e) => onChange({ territory: e.target.value })} placeholder="Brazil (GBG-LATAM)" className="mt-1" />
          </div>
          {/* Manager — autocomplete */}
          <div>
            <Label htmlFor="manager">Manager</Label>
            <div className="relative mt-1">
              <Input
                id="manager"
                value={data.manager}
                onChange={(e) => {
                  onChange({ manager: e.target.value });
                  setManagerOpen(e.target.value.length >= 2);
                }}
                onFocus={() => { if (data.manager.length >= 2) setManagerOpen(true); }}
                onBlur={() => setTimeout(() => setManagerOpen(false), 150)}
                placeholder="Manager Name"
                autoComplete="off"
              />
              {managerOpen && data.manager.length >= 2 && (() => {
                const matches = CS_AMERICAS_MANAGERS.filter((m) =>
                  m.toLowerCase().includes(data.manager.toLowerCase())
                );
                if (matches.length === 0) return null;
                return (
                  <div className="absolute z-50 mt-1 w-full max-h-48 overflow-y-auto rounded-md border border-gray-200 bg-white shadow-lg">
                    <div className="px-3 py-1.5 text-xs font-semibold text-gray-500 uppercase tracking-wide border-b border-gray-100">CS Americas Managers</div>
                    {matches.map((m) => (
                      <button
                        key={m}
                        type="button"
                        className="w-full text-left px-3 py-2 text-sm hover:bg-purple-50 hover:text-purple-700 transition-colors"
                        onMouseDown={(e) => { e.preventDefault(); handleManagerSelect(m); }}
                      >
                        {m}
                      </button>
                    ))}
                  </div>
                );
              })()}
            </div>
          </div>
          <div>
            <Label htmlFor="avatarColor">Avatar Color</Label>
            <div className="flex gap-2 mt-1 items-center">
              <input type="color" id="avatarColor" value={data.avatarColor} onChange={(e) => onChange({ avatarColor: e.target.value })} className="w-10 h-10 rounded cursor-pointer border border-gray-200" />
              <Input value={data.avatarColor} onChange={(e) => onChange({ avatarColor: e.target.value })} className="flex-1" />
            </div>
          </div>

          {/* ── In-Office Toggle ────────────────────────────── */}
          <div className="col-span-2 pt-2 border-t border-gray-100">
            <div className="flex items-center justify-between">
              <div>
                <Label className="text-sm font-medium text-gray-900">I work in-office (non-remote)</Label>
                <p className="text-xs text-gray-500 mt-0.5">Enables the In-Person Time tracking widget on your dashboard</p>
              </div>
              <button
                type="button"
                role="switch"
                aria-checked={data.isInOffice}
                onClick={() => onChange({ isInOffice: !data.isInOffice })}
                className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 ${
                  data.isInOffice ? "bg-purple-600" : "bg-gray-200"
                }`}
              >
                <span
                  className={`inline-block h-4 w-4 transform rounded-full bg-white shadow transition-transform ${
                    data.isInOffice ? "translate-x-6" : "translate-x-1"
                  }`}
                />
              </button>
            </div>
          </div>


        </div>
    </div>
  );
}

function StepUnidash({ data, onChange }: { data: WizardData; onChange: (d: Partial<WizardData>) => void }) {
  return (
    <div className="space-y-4">
      {/* Unidash name instruction */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 text-sm text-blue-800">
        <strong>How to find your Unidash name:</strong> Go to{" "}
        <a href="https://www.internalfb.com/unidash/dashboard/engagement_management_process_dashboard/dcmp_client_interaction_insights/" target="_blank" rel="noreferrer" className="underline font-medium">
          Unidash CI Dashboard
        </a>
        , click the "Sales Rep" filter, search for yourself, and copy the name exactly as shown — including accents.
      </div>
      <div>
        <Label htmlFor="salesRepName">Unidash Sales Rep Name <span className="text-red-500">*</span></Label>
        <Input id="salesRepName" value={data.salesRepName} onChange={(e) => onChange({ salesRepName: e.target.value })} placeholder="Ana Lima" className="mt-1" />
        <p className="text-xs text-gray-500 mt-1">This is used to filter CI and AI Usage data to your name only</p>
      </div>
      <div className="grid grid-cols-2 gap-4">
        <div>
          <Label htmlFor="quarter">Current Quarter</Label>
          <Input id="quarter" value={data.quarter} onChange={(e) => onChange({ quarter: e.target.value })} placeholder="Q1 2026" className="mt-1" />
        </div>
        <div>
          <Label htmlFor="ciMinTarget">Min CIs per Quarter</Label>
          <Input id="ciMinTarget" type="number" min={1} value={data.ciMinTarget} onChange={(e) => onChange({ ciMinTarget: e.target.value })} placeholder="3" className="mt-1" />
        </div>
      </div>
      {/* CRM instruction immediately above the CRM URL field */}
      <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 text-sm text-amber-800">
        <strong>How to get your CRM CI filter URL:</strong> Go to{" "}
        <a href="https://www.internalfb.com/crm/client_interactions" target="_blank" rel="noreferrer" className="underline font-medium">
          Meta CRM Client Interactions
        </a>
        , then apply these quick filters: <strong>Participant is in my BoB</strong> → <strong>This quarter</strong> → <strong>Is qualified</strong> → add filter <strong>"Participant contains any of [Your Name]"</strong>. Once the list shows only your CIs, copy the full URL from your browser address bar and paste it below.
      </div>
      <div>
        <Label htmlFor="crmCiUrl">Your CRM CI Filter URL <span className="text-gray-400 font-normal">(optional)</span></Label>
        <Input
          id="crmCiUrl"
          value={data.crmCiUrl}
          onChange={(e) => onChange({ crmCiUrl: e.target.value })}
          placeholder="https://www.internalfb.com/crm/client_interactions?view=list&filters=..."
          className="mt-1 font-mono text-xs"
        />
        <p className="text-xs text-gray-500 mt-1">Paste the URL from your browser after applying the 4 filters above. If left blank, Manus will apply the filters manually during each refresh.</p>
      </div>
    </div>
  );
}

function StepClients({ data, onChange }: { data: WizardData; onChange: (d: Partial<WizardData>) => void }) {
  const updateClient = (i: number, field: keyof Client, value: string) => {
    const clients = [...data.clients];
    clients[i] = { ...clients[i], [field]: value };
    onChange({ clients });
  };
  const addClient = () => onChange({ clients: [...data.clients, { id: "", name: "", shortName: "", tier: "A", color: "#0064E0", summary: "" }] });
  const removeClient = (i: number) => onChange({ clients: data.clients.filter((_, idx) => idx !== i) });

  return (
    <div className="space-y-4">
      <p className="text-sm text-gray-600">Add your dedicated clients. These populate the Client Content and Recommended Solutions sections.</p>

      {/* CRM Scorecard cross-reference tip */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 text-sm text-blue-800 space-y-2">
        <p>
          <strong>Find your clients via CRM Scorecard:</strong> The Scorecard shows your BoB clients grouped by <strong>Ultimate Parent</strong> — the canonical organization name used across CRM. Use it to get the exact client names before filling in the form below.
        </p>
        <ol className="list-decimal list-inside space-y-1 text-blue-700">
          <li>
            Open the{" "}
            <a
              href="https://www.internalfb.com/crm/guidance_home?currentTab=SCORECARD&granularity=ORGANIZATION&searchFilter=&guidanceType=PERFORMANCE_FIVE"
              target="_blank"
              rel="noreferrer"
              className="underline font-medium"
            >
              CRM Recommendations Hub → Scorecard
            </a>
          </li>
          <li>Set <strong>Select view</strong> to <em>Book of business view</em> to see only your clients</li>
          <li>The <strong>Ultimate Parent</strong> column lists the canonical organization names — use these as your client names below</li>
          <li><strong>Global clients</strong> (e.g., Amazon, Samsung) appear in every IC's BoB — add only the entities relevant to your territory</li>
        </ol>
      </div>
      {data.clients.map((client, i) => (
        <div key={i} className="border border-gray-200 rounded-lg p-4 space-y-3">
          <div className="flex justify-between items-center">
            <span className="font-medium text-sm text-gray-700">Client {i + 1}</span>
            {data.clients.length > 1 && (
              <button onClick={() => removeClient(i)} className="text-xs text-red-500 hover:text-red-700">Remove</button>
            )}
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>Client Name <span className="text-red-500">*</span></Label>
              <Input value={client.name} onChange={(e) => updateClient(i, "name", e.target.value)} placeholder="Magazine Luiza" className="mt-1" />
            </div>
            <div>
              <Label>Short Name</Label>
              <Input value={client.shortName} onChange={(e) => updateClient(i, "shortName", e.target.value)} placeholder="Magalu" className="mt-1" />
            </div>
            <div>
              <Label>Tier</Label>
              <select value={client.tier} onChange={(e) => updateClient(i, "tier", e.target.value)} className="mt-1 w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500">
                <option value="A+">A+</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
              </select>
            </div>
            <div>
              <Label>Brand Color</Label>
              <div className="flex gap-2 mt-1 items-center">
                <input type="color" value={client.color} onChange={(e) => updateClient(i, "color", e.target.value)} className="w-10 h-10 rounded cursor-pointer border border-gray-200" />
                <Input value={client.color} onChange={(e) => updateClient(i, "color", e.target.value)} className="flex-1" />
              </div>
            </div>
          </div>
          <div>
            <Label>One-line Summary</Label>
            <Input value={client.summary} onChange={(e) => updateClient(i, "summary", e.target.value)} placeholder="Focus areas and key projects for this client" className="mt-1" />
          </div>
        </div>
      ))}
      <Button variant="outline" onClick={addClient} className="w-full">+ Add Another Client</Button>
    </div>
  );
}

function StepAppearance({ data, onChange }: { data: WizardData; onChange: (d: Partial<WizardData>) => void }) {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-4">
        <div>
          <Label htmlFor="greeting">Greeting Language</Label>
          <select id="greeting" value={data.greeting} onChange={(e) => onChange({ greeting: e.target.value })} className="mt-1 w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500">
            <option value="Good morning">Good morning (English)</option>
            <option value="Bom dia">Bom dia (Portuguese)</option>
            <option value="Buenos días">Buenos días (Spanish)</option>
            <option value="Bonjour">Bonjour (French)</option>
          </select>
        </div>
        <div>
          <Label htmlFor="primaryColor">Accent Color</Label>
          <div className="flex gap-2 mt-1 items-center">
            <input type="color" id="primaryColor" value={data.primaryColor} onChange={(e) => onChange({ primaryColor: e.target.value })} className="w-10 h-10 rounded cursor-pointer border border-gray-200" />
            <Input value={data.primaryColor} onChange={(e) => onChange({ primaryColor: e.target.value })} className="flex-1" />
          </div>
        </div>
        <div>
          <Label htmlFor="dailyRefreshTime">Daily Refresh Time (BRT)</Label>
          <Input id="dailyRefreshTime" type="time" value={data.dailyRefreshTime} onChange={(e) => onChange({ dailyRefreshTime: e.target.value })} className="mt-1" />
        </div>
        <div>
          <Label htmlFor="timezone">Timezone</Label>
          <select id="timezone" value={data.timezone} onChange={(e) => onChange({ timezone: e.target.value })} className="mt-1 w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500">
            <option value="America/Sao_Paulo">Brazil (BRT) — São Paulo</option>
            <option value="America/Mexico_City">Mexico City (CST)</option>
            <option value="America/Argentina/Buenos_Aires">Buenos Aires (ART)</option>
            <option value="America/Bogota">Bogotá (COT)</option>
            <option value="America/Lima">Lima (PET)</option>
            <option value="America/Santiago">Santiago (CLT)</option>
            <option value="America/New_York">New York (EST)</option>
          </select>
        </div>
      </div>
    </div>
  );
}

// ── Main wizard component ─────────────────────────────────────
export default function SetupWizard() {
  const [step, setStep] = useState(1);
  const [data, setData] = useState<WizardData>(DEFAULT_DATA);
  const [copied, setCopied] = useState(false);
  const [done, setDone] = useState(false);

  const update = (partial: Partial<WizardData>) => setData((d) => ({ ...d, ...partial }));
  const configText = generateConfig(data);

  const copyConfig = async () => {
    await navigator.clipboard.writeText(configText);
    setCopied(true);
    toast.success("Config copied!", { description: "Paste it into your Manus message." });
    setTimeout(() => setCopied(false), 3000);
  };

  const [copiedMessage, setCopiedMessage] = useState(false);
  const peerFirstName = data.firstName || data.name.split(" ")[0] || "";

  // Format refresh time as human-readable (e.g. "07:00" → "7:00 AM")
  const formatRefreshTime = (time: string) => {
    const [h, m] = time.split(":").map(Number);
    const ampm = h >= 12 ? "PM" : "AM";
    const hour = h % 12 || 12;
    return `${hour}:${String(m).padStart(2, "0")} ${ampm}`;
  };
  const timezoneLabels: Record<string, string> = {
    "America/Sao_Paulo": "BRT (São Paulo)",
    "America/Mexico_City": "CST (Mexico City)",
    "America/Argentina/Buenos_Aires": "ART (Buenos Aires)",
    "America/Bogota": "COT (Bogotá)",
    "America/Lima": "PET (Lima)",
    "America/Santiago": "CLT (Santiago)",
    "America/New_York": "EST (New York)",
  };
  const refreshLabel = `${formatRefreshTime(data.dailyRefreshTime)} ${timezoneLabels[data.timezone] ?? data.timezone}`;

  const projectName = peerFirstName
    ? `${peerFirstName.toLowerCase().replace(/[^a-z0-9]/g, "")}-dashboard`
    : "my-cs-dashboard";

  const readyToSendMessage = `Hi Manus! I'm ${peerFirstName} and I'd like to set up my own Creative Shop Dashboard.

Please do the following IN ORDER:

1. CLONE THE TEMPLATE REPO
   Clone this exact repo: https://github.com/pedro-mnz/cs-dashboard-template
   Initialize it as a new Manus web project named "${projectName}" with db+server+user features.
   Do NOT build from scratch. Do NOT modify any existing project.

2. APPLY MY PERSONAL CONFIG
   Paste the config at the bottom of this message into: client/src/lib/dashboard.config.ts
   (Replace the entire file content with the config below.)

IMPORTANT — ALL INTERNAL META SOURCES REQUIRE BROWSER TAKEOVER:
   internalfb.com and workplace.com are only accessible via my personal Meta SSO session.
   Your sandbox browser cannot access these URLs directly — this is a network policy restriction, not an auth issue.
   For EACH source below: navigate to the URL in the browser, then ask me to take over the browser so I can log in with my Meta SSO. Once I confirm I'm logged in and you can see the page, take back control and scrape the data.

3. POPULATE DATA — for each source, ask me to take over the browser first, then scrape:

   a) META CALENDAR (client/src/lib/weeklyMeetingsData.ts)
      - Navigate to: https://www.internalfb.com/calendar
      - Ask me to take over the browser and log in with Meta SSO
      - Once I confirm the page is loaded, take back control
      - Read all events for the current week (Mon-Fri)
      - Write them into weeklyMeetingsData.ts following the existing file structure

   b) CRM CLIENT INTERACTIONS (client/src/lib/crmInteractionsData.ts + crmRecordsData.ts)
      - Navigate to: ${data.crmCiUrl || 'https://www.internalfb.com/crm/client_interactions'}
      - Ask me to take over the browser and log in with Meta SSO (if not already logged in from step a)
      - If no filter URL was provided, apply these filters manually: Participant is in my BoB > This quarter > Is qualified > Participant contains "${data.salesRepName}"
      - Read all CI records and write them into crmInteractionsData.ts and crmRecordsData.ts

   c) UNIDASH AI USAGE (client/src/lib/aiUsageData.ts)
      - Navigate to: https://www.internalfb.com/unidash/dashboard/engagement_management_process_dashboard/dcmp_client_interaction_insights/
      - Ask me to take over the browser if the session has expired
      - Filter by Sales Rep = "${data.salesRepName}" and current quarter
      - Read AI usage breakdown by pillar and write into aiUsageData.ts

   d) RS PIPELINE (client/src/lib/rsPipelineData.ts)
      - Navigate to: https://www.internalfb.com/crm/pipeline_management
      - Ask me to take over the browser if the session has expired
      - Read active pipeline items for my clients and write into rsPipelineData.ts

4. SAVE A CHECKPOINT and let me know it is ready so I can click Publish.

5. SET UP DAILY REFRESH
   Schedule a recurring task to run every weekday at ${refreshLabel} that re-scrapes all 4 sources above and updates the data files automatically.
   Note: The daily refresh will also require browser takeover each time to access internalfb.com.

---
MY PERSONAL CONFIG (paste into client/src/lib/dashboard.config.ts):
---

${configText}`;

  const copyReadyToSend = async () => {
    await navigator.clipboard.writeText(readyToSendMessage);
    setCopiedMessage(true);
    toast.success("Message copied!", { description: "Open a new Manus chat and paste it." });
    setTimeout(() => setCopiedMessage(false), 3000);
  };

  const [showMessagePreview, setShowMessagePreview] = useState(false);
  const [showWhatNext, setShowWhatNext] = useState(false);

  if (done) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-6">
        <div className="bg-white rounded-2xl shadow-lg max-w-2xl w-full p-8">
          {/* Success header */}
          <div className="text-center mb-8">
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <CheckCircle className="w-8 h-8 text-green-600" />
            </div>
            <h2 className="text-2xl font-bold text-gray-900 mb-2">Your config is ready!</h2>
            <p className="text-gray-500 text-sm">Follow the 3 steps below to get your dashboard live.</p>
          </div>

          {/* Step 1 — Copy message */}
          <div className="flex gap-4 mb-6">
            <div className="w-8 h-8 rounded-full bg-purple-600 text-white flex items-center justify-center text-sm font-bold flex-shrink-0 mt-0.5">1</div>
            <div className="flex-1">
              <p className="font-semibold text-gray-900 mb-1">Copy your ready-to-send message</p>
              <p className="text-sm text-gray-500 mb-3">This button copies a complete message with your config already embedded — no manual editing needed.</p>

              {/* Message preview toggle */}
              <button
                onClick={() => setShowMessagePreview((v) => !v)}
                className="flex items-center gap-1.5 text-xs text-purple-600 hover:text-purple-800 mb-3 transition-colors"
              >
                <ChevronDown className={`w-3.5 h-3.5 transition-transform ${showMessagePreview ? "rotate-180" : ""}`} />
                {showMessagePreview ? "Hide message preview" : "Preview what Manus will receive"}
              </button>
              {showMessagePreview && (
                <div className="bg-gray-50 border border-gray-200 rounded-xl p-4 mb-3 max-h-56 overflow-auto">
                  <pre className="text-xs text-gray-700 whitespace-pre-wrap font-mono leading-relaxed">{readyToSendMessage}</pre>
                </div>
              )}

              <Button onClick={copyReadyToSend} className="gap-2 bg-purple-600 hover:bg-purple-700 w-full sm:w-auto">
                {copiedMessage ? <Check className="w-4 h-4" /> : <MessageSquare className="w-4 h-4" />}
                {copiedMessage ? "Copied!" : "Copy ready-to-send message"}
              </Button>
            </div>
          </div>

          {/* Step 2 — Open Manus */}
          <div className="flex gap-4 mb-6">
            <div className="w-8 h-8 rounded-full bg-purple-600 text-white flex items-center justify-center text-sm font-bold flex-shrink-0 mt-0.5">2</div>
            <div className="flex-1">
              <p className="font-semibold text-gray-900 mb-1">Open a new Manus chat</p>
              <p className="text-sm text-gray-500 mb-3">Go to <strong>manus.im</strong>, start a new task, and paste the message you just copied. Manus will take it from there.</p>

              {/* What happens next accordion */}
              <button
                onClick={() => setShowWhatNext((v) => !v)}
                className="flex items-center gap-1.5 text-xs text-purple-600 hover:text-purple-800 mb-3 transition-colors"
              >
                <ChevronDown className={`w-3.5 h-3.5 transition-transform ${showWhatNext ? "rotate-180" : ""}`} />
                {showWhatNext ? "Hide" : "What happens next? (step by step)"}
              </button>
              {showWhatNext && (
                <div className="bg-purple-50 border border-purple-100 rounded-xl p-4 mb-3 text-sm text-purple-900">
                  <ol className="space-y-2.5 list-none">
                    {[
                      { emoji: "📁", text: "Manus clones the exact CS Dashboard template from GitHub — same design, same components, same everything" },
                      { emoji: "⚙️", text: `Manus pastes your config into dashboard.config.ts — your name, team, clients, and colors are applied instantly` },
                      { emoji: "📅", text: "Manus asks you to take over the browser so you can log in with Meta SSO — then reads your calendar, CRM, AI Usage, and RS Pipeline data" },
                      { emoji: "🎯", text: "Manus populates your CI Dashboard, Recommended Solutions, and AI Usage sections from the scraped data" },
                      { emoji: "🔒", text: "Note: internalfb.com is only accessible via your personal Meta SSO session — browser takeover is required for all 4 data sources" },
                      { emoji: "⏰", text: `Manus sets up a daily ${refreshLabel} scheduled task to keep all 4 data sources current automatically` },
                      { emoji: "🚀", text: "Manus tells you it's ready — you click Publish and your dashboard goes live at a permanent URL" },
                    ].map(({ emoji, text }, i) => (
                      <li key={i} className="flex gap-2.5 items-start">
                        <span className="text-base flex-shrink-0 mt-0.5">{emoji}</span>
                        <span className="text-xs leading-relaxed">{text}</span>
                      </li>
                    ))}
                  </ol>
                  <p className="text-xs text-purple-600 mt-3 pt-3 border-t border-purple-200">Estimated time: 5–10 minutes. All Meta-internal data is read live — nothing is fabricated.</p>
                </div>
              )}

              <a
                href="https://manus.im"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-sm font-medium text-purple-600 hover:text-purple-800 transition-colors"
              >
                <ExternalLink className="w-4 h-4" />
                Open manus.im
                <ArrowRight className="w-3 h-3" />
              </a>
            </div>
          </div>

          {/* Step 3 — Publish */}
          <div className="flex gap-4 mb-8">
            <div className="w-8 h-8 rounded-full bg-purple-600 text-white flex items-center justify-center text-sm font-bold flex-shrink-0 mt-0.5">3</div>
            <div className="flex-1">
              <p className="font-semibold text-gray-900 mb-1">Publish your dashboard</p>
              <p className="text-sm text-gray-500">Once Manus finishes setting up your project, click <strong>Publish</strong> in the Manus Management UI. Your dashboard will be live at a permanent URL you can bookmark and share.</p>
            </div>
          </div>

          {/* Divider + advanced */}
          <div className="border-t pt-5">
            <p className="text-xs text-gray-400 mb-3">Advanced: view or copy the raw config file</p>
            <div className="bg-gray-900 rounded-xl p-4 text-left mb-3 max-h-48 overflow-auto">
              <pre className="text-green-400 text-xs font-mono whitespace-pre-wrap">{configText}</pre>
            </div>
            <div className="flex gap-3">
              <Button variant="outline" onClick={copyConfig} className="gap-2 text-sm">
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied!" : "Copy raw config"}
              </Button>
              <Button variant="outline" onClick={() => { setStep(1); setDone(false); }} className="text-sm">Start Over</Button>
            </div>
          </div>

          <p className="mt-5 text-xs text-gray-400 text-center">All Meta-internal data (Calendar, AI Usage, CRM/CI, RS Pipeline) is refreshed via Manus-assisted workflow. No data is hardcoded or fabricated.</p>
          <p className="mt-2 text-xs text-gray-400 text-center">
            Something wrong or missing?{" "}
            <a
              href="https://www.workplace.com/messaging/t/pedro.menezes"
              target="_blank"
              rel="noopener noreferrer"
              className="text-purple-500 hover:text-purple-700 underline transition-colors"
            >
              Send feedback to Pedro
            </a>
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-6">
      <div className="bg-white rounded-2xl shadow-lg max-w-2xl w-full overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-[#1a1f36] to-[#2d3561] p-6 text-white">
          <div className="flex items-center gap-3 mb-1">
            <div className="w-8 h-8 bg-purple-500 rounded-lg flex items-center justify-center text-sm font-bold">CS</div>
            <span className="text-sm font-medium text-purple-300">Creative Shop Dashboard</span>
          </div>
          <h1 className="text-xl font-bold">Setup Wizard</h1>
          <p className="text-sm text-gray-400 mt-1">Configure your personal dashboard in 4 steps</p>
        </div>

        {/* Step progress */}
        <div className="px-6 pt-5">
          <div className="flex items-center gap-1">
            {STEPS.map((s, i) => {
              const Icon = s.icon;
              const isActive = s.id === step;
              const isDone = s.id < step;
              return (
                <div key={s.id} className="flex items-center flex-1">
                  <button
                    onClick={() => s.id < step && setStep(s.id)}
                    className={`flex items-center gap-1.5 px-2 py-1.5 rounded-lg text-xs font-medium transition-all flex-1 justify-center ${
                      isActive ? "bg-purple-100 text-purple-700" : isDone ? "text-green-600 cursor-pointer hover:bg-green-50" : "text-gray-400"
                    }`}
                  >
                    {isDone ? <CheckCircle className="w-3.5 h-3.5 shrink-0" /> : <Icon className="w-3.5 h-3.5 shrink-0" />}
                    <span className="hidden sm:inline truncate">{s.title}</span>
                  </button>
                  {i < STEPS.length - 1 && <div className={`w-4 h-0.5 shrink-0 ${isDone ? "bg-green-400" : "bg-gray-200"}`} />}
                </div>
              );
            })}
          </div>
        </div>

        {/* Step content */}
        <div className="p-6">
          <div className="mb-4">
            <h2 className="text-lg font-semibold text-gray-900">{STEPS[step - 1].title}</h2>
            <p className="text-sm text-gray-500">{STEPS[step - 1].description}</p>
          </div>

          {step === 1 && <StepIdentity data={data} onChange={update} />}
          {step === 2 && <StepUnidash data={data} onChange={update} />}
          {step === 3 && <StepClients data={data} onChange={update} />}
          {step === 4 && <StepAppearance data={data} onChange={update} />}
        </div>

        {/* Navigation */}
        <div className="px-6 pb-6 flex justify-between items-center border-t border-gray-100 pt-4">
          <Button variant="outline" onClick={() => setStep((s) => Math.max(1, s - 1))} disabled={step === 1} className="gap-1">
            <ChevronLeft className="w-4 h-4" /> Back
          </Button>
          <span className="text-xs text-gray-400">Step {step} of {STEPS.length}</span>
          {step < STEPS.length ? (
            <Button onClick={() => setStep((s) => s + 1)} className="gap-1 bg-purple-600 hover:bg-purple-700">
              Next <ChevronRight className="w-4 h-4" />
            </Button>
          ) : (
            <Button onClick={() => setDone(true)} className="gap-1 bg-green-600 hover:bg-green-700">
              Generate Config <CheckCircle className="w-4 h-4" />
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}
